export const courses = [
  {
    id: '1',
    title: 'React for beginners',
    description: 'Introduction to React: components, props, state',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    price: 20,
  },
  {
    id: '2',
    title: 'TypeScript for beginners',
    description: 'Basics of typing, interfaces, and generics',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    price: 25,
  },
  {
    id: '3',
    title: 'Node.js basics',
    description: 'Creating servers on Express and working with APIs',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    price: 30,
  },
  {
    id: '4',
    title: 'Next.js in production',
    description: 'SSR, SSG and performance optimization in Next.js',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    price: 35,
  },
  {
    id: '5',
    title: 'Redux Toolkit',
    description: 'Modern State Management with Redux Toolkit',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    price: 22,
  },
  {
    id: '6',
    title: 'HTML and CSS Basics',
    description: 'Page layout, flexbox and grid',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    price: 15,
  },
  {
    id: '7',
    title: 'JavaScript deep',
    description: 'Asynchrony, closures, prototypes, and contexts',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    price: 28,
  },
  {
    id: '8',
    title: 'Git and GitHub',
    description: 'Version control, pull requests, branching strategy',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    price: 12,
  },
  {
    id: '9',
    title: 'Testing in React',
    description: 'Jest and React Testing Library in practice',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    price: 26,
  },
  {
    id: '10',
    title: 'GraphQL for frontend',
    description: 'Queries, mutations, and Apollo Client',
    videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    price: 32,
  },
];
